spring:
  application:
    name: backend

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    servlet:
      path: /api


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


  mail:
    host: smtp.gmail.com
    port: 587
    username: hortoconnect@gmail.com
    password: rdyz zldu kvgp gwun
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
