name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > privatekey && chmod 600 privatekey
          scp -o StrictHostKeyChecking=no -i privatekey target/*.jar $USER@$HOST:/opt/myapp/app.jar
          ssh -o StrictHostKeyChecking=no -i privatekey $USER@$HOST << EOF
            sudo systemctl stop myapp
            sudo systemctl start myapp
          EOF